name: build and test sqr function
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: build and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: '3.1.x' 
      - run: dotnet build architekt
      - run: dotnet test architekt_test